# Generated by Django 5.2 on 2025-05-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
